runtime: python310
# entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind :$PORT main:app
# entrypoint: uvicorn --port $PORT main:app
entrypoint: gunicorn --workers 2 --worker-class uvicorn_worker.UvicornWorker --bind :$PORT main:app

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
# - url: /static
#   static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
